### ISSUE TITLE
执行错误，之前还是好的

### ISSUE THREAD

**Issue by SHYXIN** [yaoysyao/Auto_CheckIn#2]
![image](https://user-images.githubusercontent.com/55689295/209895525-5c918843-1c5b-4301-a811-23a21a4552ee.png)

**Comment by yaoysyao** [comment]
> 发现是依赖包undetected-chromedriver升级，导致错误，建议在requirements.txt，指定版本undetected-chromedriver==3.1.7

谢谢，已修复错误
